### ISSUE TITLE
Potential dependency conflicts between mlxtk and numpy

### ISSUE THREAD

**Issue by NeolithEra** [f-koehler/mlxtk#59]
Hi, as shown in the following full dependency graph of **_mlxtk_**, **_mlxtk_** requires **_numpy >=1.18,<1.19_**, **_mlxtk_** requires **_matplotlib >=3.2,<3.3_** (**_matplotlib 3.2.1_** will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_matplotlib 3.2.1_** transitively introduces **_numpy >=1.11_**.

Obviously, there are multiple version constraints set for **_numpy_** in this project. However, according to pip's _“first found wins”_ installation strategy, **_numpy 1.18.4_** (i.e., the newest version satisfying constraint **_>=1.18,<1.19_**) is the actually installed version.

Although the first found package version **_numpy 1.18.4_** just satisfies the later dependency constraint （**_numpy >=1.18,<1.19_**), such installed version is very close to the upper bound of the version constraint of numpy specified by **_matplotlib 3.2.1_**. 

Once **_matplotlib_** upgrades，its newest version will be installed. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_matplotlib_** version introduces a higher version of **_numpy_**, violating its another version constraint **_>=1.18,<1.19_**.

According to the release history of matplotlib, it habitually upgrates Numpy in its recent releases. For instance, matplotlib #15645 upgrated Numpy’s constraint from **_>=1.11 to >=1.12_**, and matplotlib #15698 upgrated Numpy’s constraint from **_>=1.12 to >=1.15_**.

As such, it is a warm warning of a potential dependency conflict issue for mlxtk.

### Dependency tree
```
mlxtk - 0.8.2
| +- colorama(install version:0.4.3 version range:>=0.4,<0.5)
| +- doit(install version:0.32.0 version range:>=0.32,<0.33)
| | +- cloudpickle(install version:1.3.0 version range:*)
| +- future(install version:0.18.2 version range:>=0.18,<0.19)
| +- h5py(install version:2.10.0 version range:>=2.10,<3.0)
| +- jinja2(install version:2.11.2 version range:>=2.10,<3.0)
| | +- MarkupSafe(install version:2.0.0a1 version range:>=0.23)
| +- matplotlib(install version:3.2.1 version range:>=3.2,<3.3)
| | +- cycler(install version:0.10.0 version range:>=0.10)
| | | +- six(install version:1.14.0 version range:*)
| | +- kiwisolver(install version:1.2.0 version range:>=1.0.1)
| | +- numpy(install version:1.18.4 version range:>=1.11)
| | +- pyparsing(install version:3.0.0a1 version range:>=2.0.1)
| | +- python-dateutil(install version:2.8.1 version range:>=2.1)
| +- numpy(install version:1.18.4 version range:>=1.18,<1.19)
| +- numpy-stl(install version:2.11.2 version range:>=2.11,<2.12)
| +- pandas(install version:0.25.3 version range:>=0.25,<0.26)
| +- pathos(install version:0.2.5 version range:>=0.2,<0.3)
| +- prompt-toolkit(install version:3.0.5 version range:>=3.0.0,<4.0.0)
| | +- wcwidth(install version:0.1.9 version range:*)
| +- pyside2(install version:5.14.2.1 version range:>=5.14,<6.0)
| +- pyyaml(install version:5.3.1 version range:>=5.1,<6.0)
| +- scipy(install version:1.4.1 version range:>=1.3,<2.0)
| +- sympy(install version:1.6rc1 version range:>=1.4,<2.0)
| +- tabulate(install version:0.8.7 version range:>=0.8,<0.9)
| +- tqdm(install version:4.46.0 version range:>=4.39,<5.0)```


Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_numpy_** to be **_>=1.18_**.
2.	Remove your direct dependency **_numpy_**, and use the **_numpy_** transitively introduced by **_matplotlib_**.
3.	Change your direct dependency **_matplotlib_** to be **_<=3.2.1_**.
@f-koehler  Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by f-koehler** [comment]
Thanks for the information.
However, I have decided to go down a different route and pin all the dependencies (wanted to do this for a while anyways).
Best,
Fabian
